// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"code.cloudfoundry.org/route-emitter/tcp/emitter"
	"code.cloudfoundry.org/route-emitter/tcp/routing_table/schema/event"
)

type FakeEmitter struct {
	EmitStub        func(routingEvents event.RoutingEvents) error
	emitMutex       sync.RWMutex
	emitArgsForCall []struct {
		routingEvents event.RoutingEvents
	}
	emitReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEmitter) Emit(routingEvents event.RoutingEvents) error {
	fake.emitMutex.Lock()
	fake.emitArgsForCall = append(fake.emitArgsForCall, struct {
		routingEvents event.RoutingEvents
	}{routingEvents})
	fake.recordInvocation("Emit", []interface{}{routingEvents})
	fake.emitMutex.Unlock()
	if fake.EmitStub != nil {
		return fake.EmitStub(routingEvents)
	} else {
		return fake.emitReturns.result1
	}
}

func (fake *FakeEmitter) EmitCallCount() int {
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return len(fake.emitArgsForCall)
}

func (fake *FakeEmitter) EmitArgsForCall(i int) event.RoutingEvents {
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return fake.emitArgsForCall[i].routingEvents
}

func (fake *FakeEmitter) EmitReturns(result1 error) {
	fake.EmitStub = nil
	fake.emitReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeEmitter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.emitMutex.RLock()
	defer fake.emitMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeEmitter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ emitter.Emitter = new(FakeEmitter)
