// This file was generated by counterfeiter
package fake_routing_table

import (
	"sync"

	"github.com/cloudfoundry-incubator/route-emitter/routing_table"
)

type FakeRoutingTable struct {
	SyncStub        func(routes routing_table.RoutesByProcessGuid, containers routing_table.ContainersByProcessGuid) routing_table.MessagesToEmit
	syncMutex       sync.RWMutex
	syncArgsForCall []struct {
		arg1 routing_table.RoutesByProcessGuid
		arg2 routing_table.ContainersByProcessGuid
	}
	syncReturns struct {
		result1 routing_table.MessagesToEmit
	}
	SetRoutesStub        func(processGuid string, routes ...string) routing_table.MessagesToEmit
	setRoutesMutex       sync.RWMutex
	setRoutesArgsForCall []struct {
		arg1 string
		arg2 []string
	}
	setRoutesReturns struct {
		result1 routing_table.MessagesToEmit
	}
	RemoveRoutesStub        func(processGuid string) routing_table.MessagesToEmit
	removeRoutesMutex       sync.RWMutex
	removeRoutesArgsForCall []struct {
		arg1 string
	}
	removeRoutesReturns struct {
		result1 routing_table.MessagesToEmit
	}
	AddOrUpdateContainerStub        func(processGuid string, container routing_table.Container) routing_table.MessagesToEmit
	addOrUpdateContainerMutex       sync.RWMutex
	addOrUpdateContainerArgsForCall []struct {
		arg1 string
		arg2 routing_table.Container
	}
	addOrUpdateContainerReturns struct {
		result1 routing_table.MessagesToEmit
	}
	RemoveContainerStub        func(processGuid string, container routing_table.Container) routing_table.MessagesToEmit
	removeContainerMutex       sync.RWMutex
	removeContainerArgsForCall []struct {
		arg1 string
		arg2 routing_table.Container
	}
	removeContainerReturns struct {
		result1 routing_table.MessagesToEmit
	}
}

func New() *FakeRoutingTable {
	return &FakeRoutingTable{}
}

func (fake *FakeRoutingTable) Sync(arg1 routing_table.RoutesByProcessGuid, arg2 routing_table.ContainersByProcessGuid) routing_table.MessagesToEmit {
	fake.syncMutex.Lock()
	defer fake.syncMutex.Unlock()
	fake.syncArgsForCall = append(fake.syncArgsForCall, struct {
		arg1 routing_table.RoutesByProcessGuid
		arg2 routing_table.ContainersByProcessGuid
	}{arg1, arg2})
	if fake.SyncStub != nil {
		return fake.SyncStub(arg1, arg2)
	} else {
		return fake.syncReturns.result1
	}
}

func (fake *FakeRoutingTable) SyncCallCount() int {
	fake.syncMutex.RLock()
	defer fake.syncMutex.RUnlock()
	return len(fake.syncArgsForCall)
}

func (fake *FakeRoutingTable) SyncArgsForCall(i int) (routing_table.RoutesByProcessGuid, routing_table.ContainersByProcessGuid) {
	fake.syncMutex.RLock()
	defer fake.syncMutex.RUnlock()
	return fake.syncArgsForCall[i].arg1, fake.syncArgsForCall[i].arg2
}

func (fake *FakeRoutingTable) SyncReturns(result1 routing_table.MessagesToEmit) {
	fake.syncReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) SetRoutes(arg1 string, arg2 ...string) routing_table.MessagesToEmit {
	fake.setRoutesMutex.Lock()
	defer fake.setRoutesMutex.Unlock()
	fake.setRoutesArgsForCall = append(fake.setRoutesArgsForCall, struct {
		arg1 string
		arg2 []string
	}{arg1, arg2})
	if fake.SetRoutesStub != nil {
		return fake.SetRoutesStub(arg1, arg2...)
	} else {
		return fake.setRoutesReturns.result1
	}
}

func (fake *FakeRoutingTable) SetRoutesCallCount() int {
	fake.setRoutesMutex.RLock()
	defer fake.setRoutesMutex.RUnlock()
	return len(fake.setRoutesArgsForCall)
}

func (fake *FakeRoutingTable) SetRoutesArgsForCall(i int) (string, []string) {
	fake.setRoutesMutex.RLock()
	defer fake.setRoutesMutex.RUnlock()
	return fake.setRoutesArgsForCall[i].arg1, fake.setRoutesArgsForCall[i].arg2
}

func (fake *FakeRoutingTable) SetRoutesReturns(result1 routing_table.MessagesToEmit) {
	fake.setRoutesReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) RemoveRoutes(arg1 string) routing_table.MessagesToEmit {
	fake.removeRoutesMutex.Lock()
	defer fake.removeRoutesMutex.Unlock()
	fake.removeRoutesArgsForCall = append(fake.removeRoutesArgsForCall, struct {
		arg1 string
	}{arg1})
	if fake.RemoveRoutesStub != nil {
		return fake.RemoveRoutesStub(arg1)
	} else {
		return fake.removeRoutesReturns.result1
	}
}

func (fake *FakeRoutingTable) RemoveRoutesCallCount() int {
	fake.removeRoutesMutex.RLock()
	defer fake.removeRoutesMutex.RUnlock()
	return len(fake.removeRoutesArgsForCall)
}

func (fake *FakeRoutingTable) RemoveRoutesArgsForCall(i int) string {
	fake.removeRoutesMutex.RLock()
	defer fake.removeRoutesMutex.RUnlock()
	return fake.removeRoutesArgsForCall[i].arg1
}

func (fake *FakeRoutingTable) RemoveRoutesReturns(result1 routing_table.MessagesToEmit) {
	fake.removeRoutesReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) AddOrUpdateContainer(arg1 string, arg2 routing_table.Container) routing_table.MessagesToEmit {
	fake.addOrUpdateContainerMutex.Lock()
	defer fake.addOrUpdateContainerMutex.Unlock()
	fake.addOrUpdateContainerArgsForCall = append(fake.addOrUpdateContainerArgsForCall, struct {
		arg1 string
		arg2 routing_table.Container
	}{arg1, arg2})
	if fake.AddOrUpdateContainerStub != nil {
		return fake.AddOrUpdateContainerStub(arg1, arg2)
	} else {
		return fake.addOrUpdateContainerReturns.result1
	}
}

func (fake *FakeRoutingTable) AddOrUpdateContainerCallCount() int {
	fake.addOrUpdateContainerMutex.RLock()
	defer fake.addOrUpdateContainerMutex.RUnlock()
	return len(fake.addOrUpdateContainerArgsForCall)
}

func (fake *FakeRoutingTable) AddOrUpdateContainerArgsForCall(i int) (string, routing_table.Container) {
	fake.addOrUpdateContainerMutex.RLock()
	defer fake.addOrUpdateContainerMutex.RUnlock()
	return fake.addOrUpdateContainerArgsForCall[i].arg1, fake.addOrUpdateContainerArgsForCall[i].arg2
}

func (fake *FakeRoutingTable) AddOrUpdateContainerReturns(result1 routing_table.MessagesToEmit) {
	fake.addOrUpdateContainerReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}

func (fake *FakeRoutingTable) RemoveContainer(arg1 string, arg2 routing_table.Container) routing_table.MessagesToEmit {
	fake.removeContainerMutex.Lock()
	defer fake.removeContainerMutex.Unlock()
	fake.removeContainerArgsForCall = append(fake.removeContainerArgsForCall, struct {
		arg1 string
		arg2 routing_table.Container
	}{arg1, arg2})
	if fake.RemoveContainerStub != nil {
		return fake.RemoveContainerStub(arg1, arg2)
	} else {
		return fake.removeContainerReturns.result1
	}
}

func (fake *FakeRoutingTable) RemoveContainerCallCount() int {
	fake.removeContainerMutex.RLock()
	defer fake.removeContainerMutex.RUnlock()
	return len(fake.removeContainerArgsForCall)
}

func (fake *FakeRoutingTable) RemoveContainerArgsForCall(i int) (string, routing_table.Container) {
	fake.removeContainerMutex.RLock()
	defer fake.removeContainerMutex.RUnlock()
	return fake.removeContainerArgsForCall[i].arg1, fake.removeContainerArgsForCall[i].arg2
}

func (fake *FakeRoutingTable) RemoveContainerReturns(result1 routing_table.MessagesToEmit) {
	fake.removeContainerReturns = struct {
		result1 routing_table.MessagesToEmit
	}{result1}
}
